### ISSUE TITLE
keystore.properties (No such file or directory)

### ISSUE THREAD

**Issue by ivanmladek** [KotlinGeekDev/Nosky#1]
Thanks for the work. 

It seems some files are missing:

```
keystore.properties (No such file or directory)
```
Anu idea what should be in it?

**Comment by KotlinGeekDev** [comment]
Hello @ivanmladek. You can either remove the code that calls it or create a keystore file, then store the information generated in a newly created keystore.properties file.

**Comment by KotlinGeekDev** [comment]
You can just remove the lines containing 'keyStoreProps'. 
And you can remove the signingConfigs {} block.

**Comment by ivanmladek** [comment]
resolved.

**Comment by KotlinGeekDev** [comment]
Cool!
