### ISSUE TITLE
Project can't compile

### ISSUE THREAD

**Issue by CristianMG** [KotlinGeekDev/Nosky#4]
Hii.

I'm getting an error because one of the library is not available at Jitpack

```
Required by:
         project :app
      > Could not resolve com.github.KotlinGeekDev.kostr:kostr-android:0.1-pre-alpha-8.
         > Could not get resource 'https://jitpack.io/com/github/KotlinGeekDev/kostr/kostr-android/0.1-pre-alpha-8/kostr-android-0.1-pre-alpha-8.pom'.
            > Could not GET 'https://jitpack.io/com/github/KotlinGeekDev/kostr/kostr-android/0.1-pre-alpha-8/kostr-android-0.1-pre-alpha-8.pom'. Received status code 521 from server: 
```
Any Idea? I would like to take a look at the project.

**Comment by KotlinGeekDev** [comment]
Hello CristianMG. There is no need to use it. You can remove that dependency.

**Comment by CristianMG** [comment]
Ok, I will test it

**Comment by KotlinGeekDev** [comment]
:+1:

**Comment by KotlinGeekDev** [comment]
Sorry. That dependency is needed. I recently had a bug which required me to put it back.

**Comment by KotlinGeekDev** [comment]
I will have to build it again.

**Comment by KotlinGeekDev** [comment]
OK @CristianMG please test with the dependency again. Should be fine now.

**Comment by KotlinGeekDev** [comment]
Well, the issue has been resolved. Closing.
